#ifndef WAITLEADER_MAPS_H
#define WAITLEADER_MAPS_H

#include <linux/types.h>

struct leader_metadata {
    __u64 start_timestamp_ns;
    __u32 origin_pid;
    __u32 suppressed_followers_count;
};

struct h2_stream_key {
    __u32 conn_id;
    __u32 stream_id;
};

enum waitleader_metric {
    WAITLEADER_METRIC_PACKETS_TOTAL = 0,
    WAITLEADER_METRIC_XDP_PASS_TOTAL,
    WAITLEADER_METRIC_XDP_DROP_TOTAL,
    WAITLEADER_METRIC_IPV4_TCP_8080_TOTAL,
    WAITLEADER_METRIC_HTTP_GET_TOTAL,
    WAITLEADER_METRIC_URI_HASH_MISS_TOTAL,
    WAITLEADER_METRIC_MALFORMED_PACKET_TOTAL,
    WAITLEADER_METRIC_NON_HTTP_PASS_TOTAL,
    WAITLEADER_METRIC_IPV6_TCP_8080_TOTAL,
    WAITLEADER_METRIC_FRAGMENTED_PASS_TOTAL,
    WAITLEADER_METRIC_RETRANSMISSION_DROP_TOTAL,
    WAITLEADER_METRIC_SK_MSG_TOTAL,
    WAITLEADER_METRIC_SK_MSG_PASS_TOTAL,
    WAITLEADER_METRIC_SK_MSG_DROP_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP1_GET_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP2_PREFACE_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP2_UNSUPPORTED_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP2_HEADERS_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP2_PATH_TOTAL,
    WAITLEADER_METRIC_TLS_HTTP2_HPACK_UNSUPPORTED_TOTAL,
    WAITLEADER_METRIC_H2_STREAM_POLICY_HIT_TOTAL,
    WAITLEADER_METRIC_H2_STREAM_POLICY_DROP_TOTAL,
    WAITLEADER_METRIC_MAX
};

#endif
