#ifndef WAITLEADER_MAPS_H
#define WAITLEADER_MAPS_H

#include <linux/types.h>

struct leader_metadata {
    __u64 start_timestamp_ns;
    __u32 origin_pid;
    __u32 suppressed_followers_count;
};

enum waitleader_metric {
    WAITLEADER_METRIC_PACKETS_TOTAL = 0,
    WAITLEADER_METRIC_XDP_PASS_TOTAL,
    WAITLEADER_METRIC_XDP_DROP_TOTAL,
    WAITLEADER_METRIC_IPV4_TCP_8080_TOTAL,
    WAITLEADER_METRIC_HTTP_GET_TOTAL,
    WAITLEADER_METRIC_URI_HASH_MISS_TOTAL,
    WAITLEADER_METRIC_MALFORMED_PACKET_TOTAL,
    WAITLEADER_METRIC_NON_HTTP_PASS_TOTAL,
    WAITLEADER_METRIC_MAX
};

#endif
